### PR TITLE
Add option to choose celery as task backend

### PR DESCRIPTION
**Pull request by swistakm**
Never worked a lot with pull requests and didn't now that all new commits will be added to it automatically. So I closed previous one and made new one.

I've fixed one issue with imports which caused that it was impossible to install using setup.py and added possibility to use celery as task backend instead of kronos. More info in updated README.
With celery it is possible to ratelimit tasks or make some locking. If so, we could get rid of .is_measuring flag which causes that skwissh sometimes stops to collect data for some servers.

### CODE REVIEW

**Comment by swistakm** [comment]
Did you take another look at this pull request?

**Comment by rsaikali** [comment]
Yes, thanks for your contributions on this project.
I will merge it soon, I'm currently working on other project and time is missing.

By the way, is this celery backend fixed the 'is_measuring' problem ?
I mean if a sensor task doesn't end, we still have the same problem isn't it : final system task (SSH command) will never end, and many system calls can be stacked ?
Or maybe there's a timeout mechanism or whatever ?

**Comment by swistakm** [comment]
Yes, there is still issue with 'is_measuring' problem. I didn't know how to achieve this in elegant way.

This is because celery backend doesn't need such workaround to ensure that tasks doesn't stack. You can define [rate limits](http://docs.celeryproject.org/en/latest/userguide/tasks.html?highlight=rate%20limit#Task.rate_limit) and timeouts to ensure that there will be no concurrent tasks and they will always quit. 

IMO get_mesures for kronos should be exeptionally wrapped with "is_measuring flag" code or we must find way to automatically kill task process after some timeout. My only idea is to use threading for timeout. I think this should be safe for kronos.

But after a while I'm not sure if I understand the whole issue, so I must ask. It is possible that final system task (SSH command) will run even if task process died (I expect that ssh connection closes)?

**Comment by rsaikali** [comment]
I need to try configuring a sensor with a blocking shell command to see what happens.
Kind of : 
`read -p "Press a key to continue"`

**Pull request closed without merging**
